export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL';
export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const ADD_MOVIE = 'ADD_MOVIE';
export const ADD_MOVIE_INIT = 'ADD_MOVIE_INIT';
export const ADD_MOVIE_START = 'ADD_MOVIE_START';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const DELETE_MOVIE_INIT = 'DELETE_MOVIE_INIT';
